name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Preload upload-artifact@v3 to resolve dependency
      - name: Preload upload-artifact (temporary fix)
        uses: actions/upload-artifact@v3
        with:
          name: dummy
          path: /dev/null

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Adjust if your built files are in a subdirectory (e.g., ./frontend)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2